raise Exception("This is a test exception")
